services:
  - type: web
    name: mini-saas
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: supersecretkey
      - key: STRIPE_SECRET_KEY
        value: sk_test_example
      - key: STRIPE_PUBLIC_KEY
        value: pk_test_example
